# Generated by Django 5.2.14 on 2026-06-01 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=15, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('caste', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Unmarried', 'Unmarried'), ('Divorced', 'Divorced')], max_length=15, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('hometown', models.CharField(blank=True, max_length=100, null=True)),
                ('current_place_of_living', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=150, null=True)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('working_status', models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Self-employed', 'Self-employed'), ('Business', 'Business'), ('Unemployed', 'Unemployed')], max_length=20, null=True)),
                ('annual_salary', models.CharField(blank=True, max_length=50, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('family_type', models.CharField(blank=True, choices=[('Nuclear', 'Nuclear'), ('Joint', 'Joint')], max_length=15, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
