# Generated by Django 5.2.14 on 2026-06-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_admin_remarks_userprofile_is_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpreferences',
            name='max_age',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='partnerpreferences',
            name='min_age',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
