# Generated by Django 5.2.15 on 2026-06-06 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_partnerpreferences_max_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver', 'timestamp'], name='profiles_me_sender__681d56_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_read'], name='profiles_me_receive_59e595_idx'),
        ),
        migrations.AddIndex(
            model_name='profilelike',
            index=models.Index(fields=['receiver', 'sender'], name='profiles_pr_receive_45b84a_idx'),
        ),
    ]
