# Generated by Django 6.0.5 on 2026-06-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
