# Generated by Django 5.2.15 on 2026-06-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_place_of_living',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='land_ownership',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('Farmer', 'Farmer'), ('Student', 'Student'), ('Software Engineer', 'Software Engineer'), ('Teacher', 'Teacher'), ('Doctor', 'Doctor'), ('Business Owner', 'Business Owner'), ('Government Job', 'Government Job'), ('Private Job', 'Private Job'), ('Other', 'Other')], max_length=150, null=True),
        ),
    ]
