# Generated by Django 5.2.15 on 2026-06-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_userprofile_current_place_of_living_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='land_ownership',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_place_of_living',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
