# Generated by Django 6.0.5 on 2026-06-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_userprofile_profile_photo'),
        ('profiles', '0008_remove_userprofile_land_ownership_and_more'),
    ]

    operations = [
    ]
