# Generated by Django 5.2.15 on 2026-06-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_merge_20260607_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='annual_salary_range',
            field=models.CharField(blank=True, choices=[('Prefer Not to Say', 'Prefer Not to Say'), ('Below ₹2 LPA', 'Below ₹2 LPA'), ('₹2–4 LPA', '₹2–4 LPA'), ('₹4–6 LPA', '₹4–6 LPA'), ('₹6–8 LPA', '₹6–8 LPA'), ('₹8–12 LPA', '₹8–12 LPA'), ('₹12–18 LPA', '₹12–18 LPA'), ('₹18–25 LPA', '₹18–25 LPA'), ('₹25–40 LPA', '₹25–40 LPA'), ('₹40–60 LPA', '₹40–60 LPA'), ('₹60 LPA–₹1 Crore', '₹60 LPA–₹1 Crore'), ('Above ₹1 Crore', 'Above ₹1 Crore')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('10th Pass', '10th Pass'), ('12th Pass', '12th Pass'), ('ITI', 'ITI'), ('Diploma', 'Diploma'), ('Undergraduate (Pursuing)', 'Undergraduate (Pursuing)'), ("Bachelor's Degree (B.A., B.Com., B.Sc., B.E./B.Tech, BBA, BCA, etc.)", "Bachelor's Degree (B.A., B.Com., B.Sc., B.E./B.Tech, BBA, BCA, etc.)"), ('Postgraduate (Pursuing)', 'Postgraduate (Pursuing)'), ("Master's Degree (M.A., M.Com., M.Sc., M.E./M.Tech, MBA, MCA, etc.)", "Master's Degree (M.A., M.Com., M.Sc., M.E./M.Tech, MBA, MCA, etc.)"), ('M.Phil.', 'M.Phil.'), ('Ph.D.', 'Ph.D.'), ('Other', 'Other')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation_category',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Software Engineer / Developer', 'Software Engineer / Developer'), ('Teacher / Professor', 'Teacher / Professor'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('Lawyer', 'Lawyer'), ('Chartered Accountant', 'Chartered Accountant'), ('Banker', 'Banker'), ('Government Employee', 'Government Employee'), ('Business Owner', 'Business Owner'), ('Entrepreneur', 'Entrepreneur'), ('Farmer', 'Farmer'), ('Sales Professional', 'Sales Professional'), ('Marketing Professional', 'Marketing Professional'), ('Designer', 'Designer'), ('Architect', 'Architect'), ('Civil Engineer', 'Civil Engineer'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Electrical Engineer', 'Electrical Engineer'), ('Data Analyst', 'Data Analyst'), ('Data Scientist', 'Data Scientist'), ('Consultant', 'Consultant'), ('Police / Defense Personnel', 'Police / Defense Personnel'), ('Content Creator', 'Content Creator'), ('Freelancer', 'Freelancer'), ('Homemaker', 'Homemaker'), ('Skilled Worker / Technician', 'Skilled Worker / Technician'), ('Retired', 'Retired'), ('Unemployed', 'Unemployed'), ('Other', 'Other')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation_other',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
