# Generated by Django 5.2.15 on 2026-06-09 16:48

import re
import django.core.validators
from django.db import migrations, models

def parse_height_to_cm(h_str):
    if not h_str:
        return None
    h_str = str(h_str).strip()
    if not h_str:
        return None
    
    # Try parsing clean integer first (e.g. 175)
    try:
        val = float(h_str)
        if val >= 100:
            return int(round(val))
    except ValueError:
        pass
        
    # Check for patterns like 5'9", 5'9'', 5'8
    match = re.match(r"(\d+)\s*'\s*(\d+)?", h_str)
    if match:
        feet = int(match.group(1))
        inches = int(match.group(2)) if match.group(2) else 0
        cm = (feet * 30.48) + (inches * 2.54)
        return int(round(cm))
        
    # Check for patterns like 5.9 or 5.0 (which usually mean 5 feet 9 inches or 5 feet 0 inches)
    match_dot = re.match(r"^(\d+)\.(\d+)$", h_str)
    if match_dot:
        feet = int(match_dot.group(1))
        inches = int(match_dot.group(2))
        # If it's less than 10, it's feet. Let's assume feet/inches.
        if feet < 10:
            cm = (feet * 30.48) + (inches * 2.54)
            return int(round(cm))
            
    # Check for simple feet like "5" or "6"
    match_feet = re.match(r"^(\d+)$", h_str)
    if match_feet:
        feet = int(match_feet.group(1))
        if feet < 10:
            cm = feet * 30.48
            return int(round(cm))
            
    return None

def clean_legacy_data(apps, schema_editor):
    UserProfile = apps.get_model('profiles', 'UserProfile')
    for profile in UserProfile.objects.all():
        # Clean height to integer string representation
        if profile.height:
            cm = parse_height_to_cm(profile.height)
            if cm:
                profile.height = str(cm)
            else:
                profile.height = None
        
        # Clean religion and caste categories
        ALLOWED_RELIGIONS = [
            'Hindu', 'Muslim', 'Christian', 'Sikh', 'Buddhist', 'Jain',
            'Zoroastrian', 'Jewish', 'Spiritual', 'Atheist', 'Agnostic', 'Prefer Not to Say'
        ]
        
        if profile.religion:
            rel = str(profile.religion).strip()
            if rel in ALLOWED_RELIGIONS:
                profile.religion_category = rel
            elif rel:
                profile.religion_category = 'Other'
                profile.religion_other = rel
                
        if profile.caste:
            cst = str(profile.caste).strip()
            STANDARD_CASTES = ['General', 'OBC', 'SC', 'ST', 'Prefer Not to Say']
            DETAILED_CASTES = ['Brahmin', 'Kshatriya', 'Vaishya', 'Shudra', 'Jat', 'Rajput', 'Maratha', 'Sunni', 'Shia', 'Catholic', 'Protestant', 'Orthodox', 'Khatri', 'Arora', 'Ramgarhia', 'Digambara', 'Shvetambara']
            if cst in STANDARD_CASTES or cst in DETAILED_CASTES:
                profile.caste_category = cst
            elif cst:
                profile.caste_category = 'Other'
                profile.caste_other = cst
                
        # Clean blood group
        if profile.blood_group:
            bg_stripped = str(profile.blood_group).strip()
            bg_upper = bg_stripped.upper()
            BLOOD_GROUP_CHOICES = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'Unknown', 'Prefer Not to Say']
            if bg_upper in BLOOD_GROUP_CHOICES:
                profile.blood_group = bg_upper
            else:
                profile.blood_group = 'Unknown'
                
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_userprofile_annual_salary_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='caste_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='caste_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='religion_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='religion_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(clean_legacy_data),
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown'), ('Prefer Not to Say', 'Prefer Not to Say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
